version: "3.9"

services:
  angular_app:
    container_name: angular_app
    image: front-angular_app:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    depends_on:
      - java_app

  java_app:
    container_name: java_app
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://java_db:3306/db-practica
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db-practica